#!/bin/sh

# grafana-db-pw.sh must have lines like the following:
#   GF_DATABASE_USER=abc
#   GF_DATABASE_PASSWORD=def123
. /dev/shm/grafana-db-pw.sh

CMD="/usr/sbin/grafana-server \
  --config=/etc/grafana/grafana.ini \
  cfg:default.paths.data=/var/lib/grafana \
  cfg:default.paths.logs=/var/log/grafana
"

exec su socrata -c "$CMD"