#!/bin/sh

# grafana-db-pw.sh must have lines like the following:
#   GF_DATABASE_USER=abc
#   GF_DATABASE_PASSWORD=def123
. /dev/shm/grafana-db-pw.sh

/bin/env_parse /etc/graphite-datasource.json.j2

exec su socrata -c "/usr/sbin/grafana-server --config /etc/grafana/grafana.ini"

curl --user admin:admin \
  -X POST \
  -H 'Content-Type: application/json;charset=UTF-8' \
  --data-binary @/etc/graphite-datasource.json \
  http://localhost:3000/api/datasources'