apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
    component: monitoring
  # annotations:
  #   prometheus.io/scrape: 'true'
spec:
  selector:
    app: grafana
    component: monitoring
  type: NodePort
  ports:
  - name: web
    port: 30043
    targetPort: 3000
    protocol: TCP
    nodePort: 30043
